#!/usr/bin/env python3
"""Author report generator for the Lean verification findings (05-feedback/).

Turns `queries/Q-NNN-*.md` + the chunk records (`02-chunks/chunks/*.yml`)
into a **self-contained** static HTML package the original author can read
without Lean and without the repository:

    report/index.html       overview: open queries, chunk status, how to respond
    report/Q-NNN.html       one page per issue: question first, the print with
                            highlighted regions, the LaTeX typeset, what Lean
                            verified, reply box
    report/reply-Q-NNN.md   plain-text reply template for answering by email
    report/assets/...       every referenced file (renders, region crops, review
                            pages, linked sources, KaTeX) — hardlinked when the
                            filesystem allows, copied otherwise

Self-containment is a gate: after writing, the script zips the report,
extracts it to a temp directory and checks that every `src`/`href` and every
CSS `url()` inside the package resolves **inside the package** (`--no-verify`
skips; `--zip` also writes `<out>.zip` for shipping). Each `--out` directory
owns its `assets/`, prunes its own generated files first, and never touches
another report directory.

Usage:
    python pipeline/05-feedback/render_report.py
    python pipeline/05-feedback/render_report.py --out report-v2 --zip

Exit codes: 0 report written and verified, 1 no/unparseable query or failed
verification, 2 output directory not writable / not generated by us.
"""

from __future__ import annotations

import argparse
import datetime
import html
import os
import re
import shutil
import struct
import sys
import tempfile
import zipfile
from pathlib import Path
from urllib.parse import unquote

HERE = Path(__file__).resolve().parent          # pipeline/05-feedback
PIPE = HERE.parent                              # pipeline
ROOT = PIPE.parent                              # repo root
QUERIES_DIR = HERE / "queries"
CHUNKS_DIR = PIPE / "02-chunks" / "chunks"
RENDER_DIR = PIPE / "01-extract" / "out"
REVIEW_DIR = RENDER_DIR / "review"
REGIONS_DIR = PIPE / "01-extract" / "regions"
VENDOR = HERE / "vendor" / "katex"
DEFAULT_OUT = HERE / "report"
MARKER = "render_report.py"
PAGE_POINTS_DEFAULT = (612.0, 792.0)

TITLE_RE = re.compile(r"^#\s+(.*)$")
HEADING_RE = re.compile(r"^##\s+(.*?)\s*$")
STATUS_RE = re.compile(r"\[(OPEN|ANSWERED|RESOLVED)\]\s*$")
CHUNK_REF_RE = re.compile(r"\b((?:L\d+|M1)-[A-Z0-9][A-Z0-9-]*)\b")
IMAGE_REF_RE = re.compile(r"[\w.+-]+(?:/[\w.+-]+)*\.(?:png|jpg|jpeg)")
PATH_REF_RE = re.compile(
    r"[\w.+-]+(?:/[\w.+-]+)*\.(?:md|py|lean|yml|yaml|png|html|log|txt|tsv)")
CLASS_MARK_RE = re.compile(r"^F([1-4])(?=[\s(:])")   # not "F1)." inside prose
QUERY_MARK_RE = re.compile(r"\b(Q-\d+)\b")
REGION_ID_RE = re.compile(r"P\d{3}-R\d+")
PAGE_FILE_RE = re.compile(r"page-(\d{3})-300dpi-full\.png$")
EXTERNAL_REF_RE = re.compile(r"^(https?:|mailto:|#|data:|javascript:)")

STYLE = """
:root{--ink:#141414;--mut:#5b6470;--line:#d9dde3;--bg:#f6f7f9;--card:#fff;
      --blue:#0b57d0;--amber:#fff6d6;--red:#ffe2e2;--green:#e6f4ea}
*{box-sizing:border-box}
body{font:15px/1.55 system-ui,-apple-system,"Segoe UI",sans-serif;margin:0;
     padding:18px 16px 40px;background:var(--bg);color:var(--ink);max-width:1100px}
a{color:var(--blue)}
h1{font-size:23px;margin:.2em 0 .35em}
h2{font-size:17px;margin:1.3em 0 .45em;border-bottom:2px solid var(--line);padding-bottom:.2em}
h3{font-size:15px;margin:1.1em 0 .35em;color:#2b3440}
h4,h5,h6{font-size:14px;margin:1em 0 .3em;color:#2b3440}
p,li{margin:.45em 0}
code,pre{font-family:ui-monospace,Consolas,"Courier New",monospace;font-size:13px}
code{background:#fff;border:1px solid var(--line);border-radius:4px;padding:1px 5px}
pre{white-space:pre-wrap;word-break:break-word;background:#fff;border:1px solid var(--line);
    border-radius:8px;padding:10px 12px}
blockquote{margin:.6em 0;padding:8px 12px;background:#fff;border-left:4px solid var(--blue);
           border-radius:0 8px 8px 0}
.chips span{display:inline-block;background:#fff;border:1px solid var(--line);
            border-radius:99px;padding:2px 10px;margin:3px 6px 0 0;font-size:13px}
.st-OPEN{background:var(--red);border-color:#f0a6a6;color:#8a1212;font-weight:600}
.st-ANSWERED{background:var(--amber);border-color:#ffe08a;color:#6d5200;font-weight:600}
.st-RESOLVED{background:var(--green);border-color:#b7e1c5;color:#1e6b3a;font-weight:600}
.st-BLOCKED{background:var(--red);border-color:#f0a6a6;color:#8a1212;font-weight:600}
.st-DONE{background:var(--green);border-color:#b7e1c5;color:#1e6b3a;font-weight:600}
.pill{display:inline-block;border:1px solid;border-radius:99px;padding:1px 8px;font-size:13px}
.card{background:var(--card);border:1px solid var(--line);border-radius:10px;
      padding:14px 16px;margin:14px 0}
.card.question{background:var(--amber);border-color:#ffe08a}
.card.answer{background:#fff;border-width:2px;border-color:var(--blue)}
.card.issue{background:var(--red);border-color:#f0a6a6}
.card h2:first-child{margin-top:0}
.note{color:var(--mut);font-size:13px}
figure{margin:12px 0;background:#fff;border:1px solid var(--line);border-radius:10px;padding:10px}
figure img{max-width:100%;height:auto;display:block;border:1px solid #eceff3}
figcaption{font-size:12.5px;color:var(--mut);margin-top:7px}
table{border-collapse:collapse;background:#fff;width:100%;font-size:14px;margin:10px 0}
th,td{border:1px solid var(--line);padding:7px 10px;text-align:left;vertical-align:top}
th{background:#eef1f5}
td.pages{white-space:nowrap}
ol.steps{padding-left:1.3em}
textarea{width:100%;min-height:150px;font:14px/1.5 ui-monospace,Consolas,monospace;
         border:1px solid var(--line);border-radius:8px;padding:10px;background:#fff}
.handwrite{display:none}
.handwrite .rule{border-bottom:1px solid #9aa4b1;height:2.1em;margin:0 0 .2em}
.warn{background:var(--red);border:1px solid #f0a6a6;border-radius:8px;padding:10px 12px}
ul.plain{list-style:none;padding-left:0}
footer{margin-top:26px;border-top:1px solid var(--line);padding-top:10px;
       color:var(--mut);font-size:12.5px}
.pagewrap{position:relative;display:block}
.pagewrap img{width:100%;height:auto}
.hl{position:absolute;border:2px solid #d3302f;background:rgba(211,48,47,.14);border-radius:2px}
.hl .tag{position:absolute;top:0;left:0;background:#d3302f;color:#fff;font-size:11px;
         line-height:1.3;padding:1px 5px;border-radius:3px 0 3px 0;white-space:nowrap}
.math-block{margin:.6em 0;text-align:center;overflow-x:auto;padding:4px 0}
.math-inline{margin:0 .12em}
@media print{
  body{max-width:none;background:#fff;padding:0}
  textarea,.noprint{display:none!important}
  .handwrite{display:block}
  .card,figure,tr{break-inside:avoid}
  .card{border-color:#999}
  a{color:#000;text-decoration:none}
}
"""

KATEX_BOOT = """
(function () {
  function renderAll() {
    var els = document.querySelectorAll('[data-tex]');
    if (!els.length || typeof katex === 'undefined') { return; }
    els.forEach(function (el) {
      var raw = el.getAttribute('data-raw') || el.textContent;
      try {
        katex.render(el.getAttribute('data-tex'), el, {
          displayMode: el.getAttribute('data-display') === '1',
          throwOnError: true, strict: false, trust: false
        });
      } catch (e) {
        el.textContent = raw;            // never let a formula hide the text
        el.className = 'code';
        el.style.fontFamily = 'ui-monospace,Consolas,monospace';
        el.style.fontSize = '13px';
      }
    });
  }
  // inline scripts ignore `defer`, so katex.min.js may not exist yet:
  // wait for DOMContentLoaded, which fires after deferred scripts ran.
  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', renderAll);
  } else {
    renderAll();
  }
})();
"""


# --------------------------------------------------------------------------- #
# parsers
# --------------------------------------------------------------------------- #

def parse_query(path: Path) -> dict:
    """Query markdown -> {id, title, status, chunk, sections, text}."""
    text = path.read_text(encoding="utf-8")
    lines = text.splitlines()
    first = lines[0] if lines else ""
    if not TITLE_RE.match(first) or not STATUS_RE.search(first):
        raise ValueError(f"{path.name}: first line must be '# Q-NNN … [OPEN]'")
    title = STATUS_RE.sub("", TITLE_RE.match(first).group(1)).strip()
    title = re.sub(r"^(Q-\d+)\s+", "", title)      # id is rendered separately
    status = STATUS_RE.search(first).group(1)
    qid = QUERY_MARK_RE.search(first).group(0) if QUERY_MARK_RE.search(first) else path.stem

    sections: dict[str, str] = {}
    current, buf = None, []
    for line in lines[1:]:
        m = HEADING_RE.match(line)
        if m:
            if current is not None:
                sections[current] = "\n".join(buf).strip()
            current, buf = m.group(1), []
        elif current is not None:
            buf.append(line)
    if current is not None:
        sections[current] = "\n".join(buf).strip()

    head = sections.get("Chunk + PDF ref", "")
    m = CHUNK_REF_RE.search(head) or CHUNK_REF_RE.search(text)
    return {"id": qid, "title": title, "status": status,
            "chunk": m.group(1) if m else None,
            "sections": sections, "text": text, "file": path.name}


def parse_chunk(path: Path) -> dict:
    """Chunk YAML subset: flat keys plus `key: |` block scalars (no PyYAML)."""
    record: dict = {"_file": path.name}
    lines = path.read_text(encoding="utf-8").splitlines()
    i = 0
    while i < len(lines):
        line = lines[i]
        if line.strip() and not line.startswith((" ", "\t", "#")):
            m = re.match(r"^([A-Za-z_][A-Za-z0-9_]*):\s*(.*)$", line)
            if m:
                key, rest = m.group(1), m.group(2).strip()
                if rest in ("|", "|-", "|+", ">", ">-", ">+"):
                    block, i = [], i + 1
                    while i < len(lines) and (not lines[i].strip()
                                              or lines[i].startswith((" ", "\t"))):
                        block.append(lines[i][2:] if lines[i][:2] == "  " else "")
                        i += 1
                    record[key] = "\n".join(block).strip("\n")
                    continue
                record[key] = rest.strip('"')
        i += 1
    return record


def chunk_classes(rec: dict) -> list[tuple[str, str]]:
    """F1–F4 classification paragraphs from the `author_steps` block."""
    lines = rec.get("author_steps", "").splitlines()
    out: list[tuple[str, str]] = []
    for idx, line in enumerate(lines):
        indent = len(line) - len(line.lstrip())
        if indent or not CLASS_MARK_RE.match(line):
            continue
        para = [line.strip()]
        for nxt in lines[idx + 1:]:
            nxt_indent = len(nxt) - len(nxt.lstrip())
            if nxt.strip() and nxt_indent <= indent:
                break
            if nxt.strip():
                para.append(nxt.strip())
        out.append((f"F{CLASS_MARK_RE.match(line.strip()).group(1)}", " ".join(para)))
    return out


def chunk_queries(rec: dict) -> list[str]:
    return sorted(set(QUERY_MARK_RE.findall(rec.get("author_steps", ""))))


def page_list(rec: dict | None) -> str:
    if not rec:
        return "—"
    raw = str(rec.get("pdf_pages", "")).strip()
    return raw.strip("[]") if raw else "—"


def parse_region_record(page: int) -> dict[str, dict]:
    """`01-extract/regions/pNNN.yml` -> {P0NNN-RM: {rect, crop, latex}}."""
    yml = REGIONS_DIR / f"p{page:03d}.yml"
    if not yml.exists():
        return {}
    out: dict[str, dict] = {}
    lines = yml.read_text(encoding="utf-8").splitlines()
    cur: str | None = None
    i = 0
    while i < len(lines):
        line = lines[i]
        m = re.match(r"^\s*-\s+id:\s*(\S+)", line)
        if m:
            cur = f"P{page:03d}-{m.group(1)}"
            out[cur] = {"rect": None, "crop": None, "latex": ""}
            i += 1
            continue
        if cur:
            m = re.match(r"^\s*rect:\s*\[([^\]]*)\]", line)
            if m:
                try:
                    out[cur]["rect"] = [float(x) for x in m.group(1).split(",")]
                except ValueError:
                    out[cur]["rect"] = None
            m = re.match(r"^\s*crop:\s*(\S+)", line)
            if m:
                out[cur]["crop"] = m.group(1)
            if re.match(r"^\s*latex:\s*\|", line):
                indent = len(line) - len(line.lstrip())
                buf = []
                i += 1
                while i < len(lines):
                    nxt = lines[i]
                    nindent = len(nxt) - len(nxt.lstrip())
                    if nxt.strip() and nindent <= indent:
                        break
                    buf.append(nxt[indent + 2:] if len(nxt) > indent + 2 else "")
                    i += 1
                out[cur]["latex"] = "\n".join(buf).strip()
                continue
        i += 1
    return out


def page_points(page: int) -> tuple[float, float]:
    """Page size in PDF points from any region crop JSON for that page."""
    import json
    for j in sorted(RENDER_DIR.glob(f"page-{page:03d}-300dpi-region-*.json")):
        try:
            data = json.loads(j.read_text(encoding="utf-8"))
        except (OSError, ValueError):
            continue
        rect = data.get("page_rect_points")
        if isinstance(rect, list) and len(rect) == 4:
            return float(rect[2] - rect[0]), float(rect[3] - rect[1])
    return PAGE_POINTS_DEFAULT


def png_size(path: Path) -> tuple[int, int]:
    data = path.read_bytes()[:24]
    if len(data) >= 24 and data[12:16] == b"IHDR":
        return struct.unpack(">II", data[16:24])
    return 0, 0


# --------------------------------------------------------------------------- #
# asset packing (self-containment)
# --------------------------------------------------------------------------- #

class Pack:
    """Copies/hardlinks every referenced file under <out>/assets, mirroring the
    pipeline-relative path, and reports the URL to use inside the report."""

    def __init__(self, out_dir: Path):
        self.out = out_dir
        self.assets = out_dir / "assets"
        self.map: dict[Path, Path] = {}
        self.html_queue: list[Path] = []
        self.css_queue: list[Path] = []
        self.declined: list[str] = []
        self._extern_names: dict[str, Path] = {}

    # -- link policy -------------------------------------------------------
    _SRC_LIST_RE = re.compile(r"src:([^;}]+)")
    _ENTRY_RE = re.compile(r"url\(([^)]+)\)\s*format\(([^)]+)\)")

    @classmethod
    def _trim_font_fallbacks(cls, css: str, base: Path) -> str:
        """Drop `url(...) format(...)` font entries whose file is not shipped,
        touching ONLY the inside of `src:` lists — a minified stylesheet puts
        `}@font-face{...` between entries, so a greedy pattern here destroys
        rules (that is what silently unbound the KaTeX fonts)."""
        def fix(m: re.Match) -> str:
            body = m.group(1)
            if "url(" not in body or "local(" in body:
                return m.group(0)
            entries = cls._ENTRY_RE.findall(body)
            if not entries:
                return m.group(0)
            keep = [f"url({u}) format({f})" for u, f in entries
                    if (base / u.strip("'\"")).is_file()]
            if not keep or len(keep) == len(entries):
                return m.group(0)
            return "src:" + ",".join(keep)

        return cls._SRC_LIST_RE.sub(fix, css)

    def can_link(self, src: Path) -> bool:
        if not src.is_file():
            return False
        if src.resolve() == (REVIEW_DIR / "index.html").resolve():
            # the review index links every manual page: packing it would drag
            # in the whole review surface; cite the individual pages instead.
            self.declined.append(str(src))
            return False
        return True

    def dest_for(self, src: Path) -> Path:
        try:
            rel = src.resolve().relative_to(PIPE.resolve())
            return self.assets / rel
        except ValueError:
            name = src.name
            prev = self._extern_names.get(name)
            if prev is not None and prev != src:
                name = f"{src.stem}-{abs(hash(str(src))) % 10 ** 8}{src.suffix}"
            self._extern_names[name] = src
            return self.assets / "_external" / name

    def link(self, src: Path) -> str:
        """Stage `src` into the package; return its URL relative to <out>."""
        src = src.resolve()
        if src.is_relative_to(self.out.resolve()):
            return _rel(src, self.out)
        if src in self.map:
            return _rel(self.map[src], self.out)
        if not src.is_file():
            raise FileNotFoundError(src)
        dest = self.dest_for(src)
        dest.parent.mkdir(parents=True, exist_ok=True)
        try:
            if src.suffix.lower() == ".css":
                # derived copy: keep only the font formats actually shipped
                # (KaTeX css lists woff2/woff/ttf; we ship woff2 only), so the
                # package never references a file it does not contain — and
                # never loses the @font-face/.katex rules that bind them.
                text = src.read_text(encoding="utf-8", errors="surrogateescape")
                derived = self._trim_font_fallbacks(text, src.parent)
                dest.write_text(derived, encoding="utf-8", errors="surrogateescape",
                                newline="\n")
                self.map[src] = dest
                self.css_queue.append(src)
                return _rel(dest, self.out)
            if dest.exists() and dest.stat().st_size != src.stat().st_size:
                dest.unlink()
            if not dest.exists():
                try:
                    os.link(src, dest)             # hardlink: no extra bytes
                except OSError:
                    shutil.copy2(src, dest)        # fallback (cross-device etc.)
        except OSError as exc:
            raise OSError(f"cannot stage {src}: {exc}") from exc
        self.map[src] = dest
        if src.suffix.lower() in (".html", ".htm"):
            self.html_queue.append(src)
        return _rel(dest, self.out)

    # -- closure over copied HTML -----------------------------------------
    def closure(self) -> int:
        """Copy whatever the *copied* HTML/CSS files reference (review pages →
        their renders/crops, KaTeX css → its woff2 fonts), so the package keeps
        working after a move."""
        seen: set[Path] = set()
        added = 0
        queue = list(self.html_queue) + list(self.css_queue)
        while queue:
            page = queue.pop()
            if page in seen:
                continue
            seen.add(page)
            text = page.read_text(encoding="utf-8", errors="replace")
            for ref in _refs_in(text):
                if EXTERNAL_REF_RE.match(ref):
                    continue
                clean = unquote(ref.split("#")[0].split("?")[0])
                if not clean:
                    continue
                target = (page.parent / clean).resolve()
                if not target.is_file():
                    continue
                if PIPE.resolve() not in target.parents and target.parent != PIPE.resolve():
                    continue                       # never pull files outside pipeline/
                if target in self.map:
                    continue
                before = len(self.map)
                try:
                    self.link(target)
                except OSError:
                    continue
                added += len(self.map) - before
                if target.suffix.lower() in (".html", ".htm", ".css"):
                    queue.append(target)
        return added


# --------------------------------------------------------------------------- #
# region highlights
# --------------------------------------------------------------------------- #

def highlights_for(query: dict, rec: dict | None) -> dict[int, list[tuple[list[float], str]]]:
    """page -> [(rect_points, region_id)] for the regions this query points at."""
    ids = REGION_ID_RE.findall(query["text"])
    if not ids and rec:
        ids = [s.strip() for s in str(rec.get("regions", "")).split(",") if s.strip()]
    pages = sorted({int(rid[1:4]) for rid in ids})
    out: dict[int, list[tuple[list[float], str]]] = {}
    for page in pages:
        regions = parse_region_record(page)
        sel = [(regions[rid]["rect"], rid) for rid in ids
               if int(rid[1:4]) == page and rid in regions and regions[rid]["rect"]]
        if sel:
            out[page] = sel
    return out


def highlight_latex(highlights: dict[int, list]) -> list[tuple[str, list[str]]]:
    """[(region_id, [display equations])] for the typeset-print card."""
    out = []
    for page in sorted(highlights):
        regions = parse_region_record(page)
        for _, rid in highlights[page]:
            tex = regions.get(rid, {}).get("latex", "")
            blocks = latex_blocks(tex)
            if blocks:
                out.append((rid, blocks))
    return out


def latex_blocks(tex: str) -> list[str]:
    if not tex.strip():
        return []
    found = re.findall(r"\\\[.*?\\\]", tex, re.S)
    if not found:
        return [tex.strip()]
    return [b[2:-2].strip() for b in found if b[2:-2].strip()]


# --------------------------------------------------------------------------- #
# math (KaTeX)
# --------------------------------------------------------------------------- #

_TEX_MAP = [
    ("≢", r"\not\equiv"), ("≡", r"\equiv"), ("∤", r"\nmid"), ("∣", r"\mid"),
    ("⋮̸", r"\not\vdots"), ("⋮", r"\vdots"), ("ℤ", r"\mathbb{Z}"),
    ("ℕ", r"\mathbb{N}"), ("²", r"^{2}"), ("³", r"^{3}"), ("−", "-"),
    ("–", "-"), ("≤", r"\le"), ("≥", r"\ge"), ("≠", r"\ne"), ("∈", r"\in"),
    ("⇒", r"\Rightarrow"), ("→", r"\to"), ("↑", r"\uparrow"),
    ("·", r"\cdot "), ("…", r"\ldots "), ("*", " "),
]


def text_to_tex(s: str) -> str | None:
    """Best-effort conversion of a plain-text math fragment; None = leave alone."""
    if "/" in s or "\\" in s:            # paths / already-latex
        return None
    if not re.search(r"[\^≢≡∤∣²³]", s) and not re.search(r"\bmod\b", s):
        return None
    t = s
    for a, b in _TEX_MAP:
        t = t.replace(a, b)
    t = re.sub(r"\(mod\s+([^)]+)\)", r"\\pmod{\1}", t)
    t = re.sub(r"\^([A-Za-z0-9])", r"^{\1}", t)
    t = re.sub(r"\s+", " ", t).strip()
    return t or None


def math_span(raw: str) -> str:
    """Inline math element with the raw text as no-JS/no-KaTeX fallback."""
    tex = text_to_tex(raw)
    if not tex:
        return f"<code>{html.escape(raw)}</code>"
    return (f'<span class="math-inline" data-tex="{html.escape(tex, quote=True)}" '
            f'data-raw="{html.escape(raw, quote=True)}">{html.escape(raw)}</span>')


def math_block(tex: str, raw: str | None = None) -> str:
    raw = raw if raw is not None else tex
    return (f'<div class="math-block" data-display="1" '
            f'data-tex="{html.escape(tex, quote=True)}" '
            f'data-raw="{html.escape(raw, quote=True)}">{html.escape(raw)}</div>')


def head_assets(pack: Pack, title: str, has_math: bool) -> str:
    parts = ['<meta charset="utf-8">',
             '<meta name="viewport" content="width=device-width, initial-scale=1">',
             f"<title>{html.escape(title)}</title>",
             "<style>" + STYLE + "</style>"]
    if has_math:
        parts += [
            f'<link rel="stylesheet" href="{html.escape(pack.link(VENDOR / "katex.min.css"), quote=True)}">',
            f'<script defer src="{html.escape(pack.link(VENDOR / "katex.min.js"), quote=True)}"></script>',
            "<script defer>\n" + KATEX_BOOT + "\n</script>",
        ]
    return "\n".join(parts)


# --------------------------------------------------------------------------- #
# markdown -> html (subset: headings, fences, lists, quotes, links, code)
# --------------------------------------------------------------------------- #

def _rel(target: Path, start: Path) -> str:
    """Relative URL from directory `start` to file `target`."""
    return Path(os.path.relpath(target, start)).as_posix()


def _code_span(escaped: str, pack: Pack) -> str:
    """`code` -> <code>, linked and packed when it names an existing repo file."""
    if PATH_REF_RE.fullmatch(escaped):
        cand = ROOT / escaped
        if pack.can_link(cand):
            return (f'<a href="{html.escape(pack.link(cand), quote=True)}">'
                    f"<code>{escaped}</code></a>")
    return f"<code>{escaped}</code>"


def _inline(segment: str, pack: Pack) -> str:
    """Bold, links, inline code and math inside an already-escaped segment."""
    parts = re.split(r"(`[^`]+`)", segment)
    for i, part in enumerate(parts):
        if part.startswith("`") and part.endswith("`") and len(part) > 2:
            inner = re.match(r"`(.*)`", part, re.S).group(1)
            parts[i] = math_span(html.unescape(inner)) if text_to_tex(html.unescape(inner)) \
                else _code_span(inner, pack)
            continue

        def sub_link(m: re.Match, _p=part) -> str:
            label, target = m.group(1), m.group(2)
            if EXTERNAL_REF_RE.match(target):
                return f'<a href="{html.escape(target, quote=True)}">{label}</a>'
            cand = ROOT / target
            if pack.can_link(cand):
                return (f'<a href="{html.escape(pack.link(cand), quote=True)}">'
                        f"{label}</a>")
            return label

        part = re.sub(r"\[([^\]]+)\]\(([^)\s]+)\)", sub_link, part)
        part = re.sub(r"\*\*([^*]+)\*\*", r"<b>\1</b>", part)
        parts[i] = part
    return "".join(parts)


def md_to_html(text: str, pack: Pack) -> str:
    out: list[str] = []
    para: list[str] = []
    code_buf: list[str] | None = None
    list_mode: str | None = None

    def flush_para() -> None:
        if para:
            out.append("<p>" + _inline(" ".join(para), pack) + "</p>")
            para.clear()

    def close_list() -> None:
        nonlocal list_mode
        if list_mode:
            out.append(f"</{list_mode}>")
            list_mode = None

    for raw in text.splitlines():
        line = raw.rstrip()
        if code_buf is not None:
            if line.strip().startswith("```"):
                out.append("<pre>" + html.escape("\n".join(code_buf)) + "</pre>")
                code_buf = None
            else:
                code_buf.append(raw)
            continue
        if line.strip().startswith("```"):
            flush_para()
            close_list()
            code_buf = []
            continue
        if not line.strip():
            flush_para()
            close_list()
            continue
        m = re.match(r"^(#{1,6})\s+(.*)$", line)
        if m:
            flush_para()
            close_list()
            lvl = min(len(m.group(1)) + 1, 6)      # query text is sub-headings
            out.append(f"<h{lvl}>{_inline(html.escape(m.group(2)), pack)}</h{lvl}>")
            continue
        if line.startswith(">"):
            flush_para()
            close_list()
            out.append("<blockquote>" + _inline(html.escape(line.lstrip("> ")), pack)
                       + "</blockquote>")
            continue
        if re.match(r"^\s*[-*]\s+", line):
            flush_para()
            if list_mode != "ul":
                close_list()
                out.append("<ul>")
                list_mode = "ul"
            item = re.sub(r"^\s*[-*]\s+", "", line)
            out.append("<li>" + _inline(html.escape(item), pack) + "</li>")
            continue
        if re.match(r"^\s*\d+[.)]\s+", line):
            flush_para()
            if list_mode != "ol":
                close_list()
                out.append("<ol>")
                list_mode = "ol"
            item = re.sub(r"^\s*\d+[.)]\s+", "", line)
            out.append("<li>" + _inline(html.escape(item), pack) + "</li>")
            continue
        close_list()
        para.append(html.escape(line))
    if code_buf is not None:
        out.append("<pre>" + html.escape("\n".join(code_buf)) + "</pre>")
    flush_para()
    close_list()
    return "\n".join(out)


# --------------------------------------------------------------------------- #
# figures
# --------------------------------------------------------------------------- #

def _figure(src_url: str, caption: str, inner_img: str | None = None) -> str:
    img = inner_img if inner_img else f'<img src="{html.escape(src_url, quote=True)}" ' \
                                       f'alt="{html.escape(caption)}" loading="lazy">'
    return (f"<figure>{img}<figcaption>{html.escape(caption)} — "
            f'<a href="{html.escape(src_url, quote=True)}">open full size</a>'
            f"</figcaption></figure>")


def overlay_figure(page: int, src_url: str,
                   boxes: list[tuple[list[float], str]]) -> str:
    w, h = page_points(page)
    tags = []
    for (x0, y0, x1, y1), rid in boxes:
        left, top = x0 / w * 100, y0 / h * 100
        width, height = (x1 - x0) / w * 100, (y1 - y0) / h * 100
        tags.append(
            f'<div class="hl" title="{html.escape(rid)}" '
            f'style="left:{left:.3f}%;top:{top:.3f}%;width:{width:.3f}%;'
            f'height:{height:.3f}%"><span class="tag">{html.escape(rid)}</span></div>')
    img = (f'<div class="pagewrap"><img src="{html.escape(src_url, quote=True)}" '
           f'alt="PDF page {page} with {html.escape(", ".join(r for _, r in boxes))} highlighted" '
           f'loading="lazy">{" ".join(tags)}</div>')
    label = ", ".join(rid for _, rid in boxes)
    return (f"<figure>{img}<figcaption>PDF trang / page {page} — vùng hỏi "
            f"/ highlighted: {html.escape(label)} (khung đỏ = rect của record "
            f"region) — <a href=\"{html.escape(src_url, quote=True)}\">open full size</a>"
            f"</figcaption></figure>")


def evidence_figures(query: dict, rec: dict | None, pack: Pack) -> str:
    """Overlay figures for the cited regions + every other image the query or
    the chunk record names."""
    highlights = highlights_for(query, rec)
    figs: list[str] = []
    covered: set[str] = set()
    for page in sorted(highlights):
        full = RENDER_DIR / f"page-{page:03d}-300dpi-full.png"
        if full.exists():
            figs.append(overlay_figure(page, pack.link(full), highlights[page]))
            covered.add(full.name)
        else:                                   # no full render: fall back to crops
            for _, rid in highlights[page]:
                rec_regions = parse_region_record(page)
                crop = rec_regions.get(rid, {}).get("crop")
                if crop and (RENDER_DIR / crop).exists():
                    figs.append(_figure(pack.link(RENDER_DIR / crop),
                                        f"PDF page {page} region {rid} (crop)"))

    for ref in IMAGE_REF_RE.findall(query["text"]):
        cand = ROOT / ref if ref.startswith("pipeline/") else HERE / ref
        if not cand.exists():
            cand = RENDER_DIR / Path(ref).name
        if cand.exists() and cand.name not in covered:
            covered.add(cand.name)
            figs.append(_figure(pack.link(cand), f"{query['id']} evidence — {cand.name}"))
    if rec:
        for render in str(rec.get("renders", "")).split():
            cand = RENDER_DIR / render
            if cand.exists() and cand.name not in covered:
                covered.add(cand.name)
                figs.append(_figure(pack.link(cand),
                                    f"{rec.get('id', 'chunk')} — PDF page(s) "
                                    f"{page_list(rec)}, render {render}"))
    if not figs:
        return ""
    return ('<div class="card"><h2>Trang in / The printed pages '
            "(bản in là căn cứ — the print is authoritative)</h2>" + "".join(figs) + "</div>")


def typeset_card(query: dict, rec: dict | None, pack: Pack) -> str:
    blocks = highlight_latex(highlights_for(query, rec))
    if not blocks:
        return ""
    body = []
    for rid, eqs in blocks:
        body.append(f"<h3>{html.escape(rid)}</h3>")
        body.extend(math_block(tex) for tex in eqs)
    return ('<div class="card"><h2>Bản in đã dựng chữ / The printed lines, '
            'typeset (LaTeX từ record region)</h2>' + "".join(body) + "</div>")


# --------------------------------------------------------------------------- #
# page builders
# --------------------------------------------------------------------------- #

def question_lead(query: dict) -> str:
    body = query["sections"].get("Question for the author", "")
    m = re.search(r"^(?P<p>.*?)\n\s*\n", body, re.S)
    lead = (m.group("p") if m else body).strip()
    return lead or "(question text missing)"


def build_issue_page(query: dict, rec: dict | None, pack: Pack) -> str:
    out = pack.out
    chunk_id = query["chunk"] or "—"
    decls = [d.strip() for d in str(rec.get("lean_decls", "")).split(",") if d.strip()] \
        if rec else []

    class_html = ""
    classes = chunk_classes(rec) if rec else []
    if classes:
        items = "".join(f"<li><b>{cls}</b> — {md_to_html(para, pack)}</li>"
                        for cls, para in classes)
        class_html = (
            '<div class="card"><h2>Ghi chú phân loại / Classification notes '
            "(internal)</h2><ul>" + items + "</ul>"
            '<p class="note">F3 = a gap we filled from your own material (no new '
            "assumption). F4 = a proof step Lean could not verify; it needs your "
            "answer above.</p></div>")

    fig_html = evidence_figures(query, rec, pack)
    math_html = typeset_card(query, rec, pack)

    review_html = ""
    cited = sorted(set(re.findall(r"review/(page-\d+\.html)", query["text"])))
    if cited:
        links = ", ".join(
            f'<a href="{html.escape(pack.link(REVIEW_DIR / name), quote=True)}">'
            f"{name}</a>" for name in cited if pack.can_link(REVIEW_DIR / name))
        if links:
            review_html = (f'<p class="note">Bản xem xét / review display for this '
                           f"page(s): {links} — render bên trái là căn cứ.</p>")

    question_card = (
        '<div class="card question"><h2>❓ Câu hỏi dành cho tác giả / '
        "Question for the author</h2>"
        + md_to_html(question_lead(query), pack)
        + f'<p class="note">Trả lời ở cuối trang / reply at the bottom of this page, '
          f'or edit <code>reply-{query["id"]}.md</code> and send it back.</p></div>')

    in_card = {"Question for the author", "Chunk + PDF ref",
               "What we formalized", "What failed"}
    body_parts = [
        f"<h3>{html.escape(name)}</h3>" + md_to_html(body, pack)
        for name, body in query["sections"].items()
        if name not in in_card and body.strip()]

    decl_html = ""
    if decls:
        decl_html = ("<h3>Đã kiểm chứng trong Lean / verified declarations</h3><ul class='plain'>"
                     + "".join(f"<li><code>{html.escape(d)}</code></li>" for d in decls)
                     + "</ul>")

    body = f"""
<p class="noprint"><a href="index.html">← Danh mục / report index</a></p>
<h1>{html.escape(query['id'])} · {html.escape(query['title'])}</h1>
<div class="chips">
  <span class="st-{query['status']}">{query['status']}</span>
  <span><b>chunk</b> {html.escape(chunk_id)}</span>
  <span><b>PDF pages</b> {html.escape(page_list(rec))}</span>
  <span><b>decls</b> {len(decls)}</span>
  <span><b>file</b> {html.escape(query['file'])}</span>
</div>
{question_card}
<div class="card issue">
<h2>⚠ Vấn đề / What Lean could not verify</h2>
{md_to_html(query['sections'].get('What failed', '(section missing)'), pack)}
</div>
<div class="card">
<h2>Bản in nói gì / What the print says</h2>
{md_to_html(query['sections'].get('Chunk + PDF ref', '(section missing)'), pack)}
{review_html}
</div>
{math_html}
{fig_html}
<div class="card">
<h2>Phát biểu đã kiểm chứng / What we formalized (the statement Lean checks)</h2>
{md_to_html(query['sections'].get('What we formalized', '(section missing)'), pack)}
{decl_html}
</div>
{''.join(body_parts)}
{class_html}
<div class="card answer">
<h2>✍️ Trả lời của tác giả / Author's reply</h2>
<p class="note">Gõ vào ô dưới đây rồi copy vào email, hoặc sửa tệp
<code>reply-{html.escape(query['id'])}.md</code>. / Type below and paste into an
email, or edit the reply template file.</p>
<textarea spellcheck="false" placeholder="{html.escape(query['id'])}: câu trả lời của quý vị / your answer …"></textarea>
<div class="handwrite">
  <p class="note">In trang này và viết tay / print this page and write by hand:</p>
  <div class="rule"></div><div class="rule"></div><div class="rule"></div>
  <div class="rule"></div><div class="rule"></div><div class="rule"></div>
</div>
</div>
<footer>
Sinh từ / generated by <code>pipeline/05-feedback/render_report.py</code> on
{datetime.date.today().isoformat()} — nguồn / sources:
<code>{html.escape(query['file'])}</code>{f", <code>{html.escape(rec['_file'])}</code>" if rec else ""}.
Không cần Lean để trả lời / no Lean required to answer.
</footer>"""

    title = f"{query['id']} — {query['title']}"
    return ("<!doctype html>\n"
            f'<html lang="vi">\n<head>\n{head_assets(pack, title, "data-tex" in body)}\n'
            f"</head>\n<body>\n{body}\n</body>\n</html>\n")


def build_index(queries: list[dict], recs: dict[str, dict], warnings: list[str],
                pack: Pack) -> str:
    rows = []
    for q in queries:
        rec = recs.get(q["chunk"] or "")
        rows.append(
            "<tr>"
            f'<td><a href="{q["id"]}.html"><b>{html.escape(q["id"])}</b></a></td>'
            f"<td>{html.escape(q['title'])}</td>"
            f'<td><span class="pill st-{q["status"]}">{q["status"]}</span></td>'
            f"<td>{html.escape(q['chunk'] or '—')}</td>"
            f'<td class="pages">{html.escape(page_list(rec))}</td>'
            f'<td><a href="reply-{q["id"]}.md">reply template</a></td>'
            "</tr>")

    chunk_rows = []
    for cid in sorted(recs):
        rec = recs[cid]
        decls = [d for d in str(rec.get("lean_decls", "")).split(",") if d.strip()]
        status = str(rec.get("status", "?"))
        links = ", ".join(f'<a href="{q}.html">{q}</a>' for q in chunk_queries(rec)) or "—"
        chunk_rows.append(
            "<tr>"
            f"<td><b>{html.escape(cid)}</b></td>"
            f'<td><span class="pill st-{status}">{status}</span></td>'
            f"<td>{html.escape(page_list(rec))}</td>"
            f"<td>{len(decls)} decls</td>"
            f"<td>{links}</td>"
            "</tr>")

    warn_html = ""
    if warnings:
        warn_html = ('<div class="warn"><b>Ghi chú kỹ thuật / internal checks '
                     "(report may be incomplete)</b><ul>"
                     + "".join(f"<li>{html.escape(w)}</li>" for w in warnings)
                     + "</ul></div>")

    open_q = sum(1 for q in queries if q["status"] == "OPEN")
    blocked = [c for c, r in recs.items() if str(r.get("status")) == "BLOCKED"]

    body = f"""
<h1>Báo cáo kiểm chứng — các câu hỏi dành cho tác giả</h1>
<p class="note">Verification report — open questions for the author
(generated {datetime.date.today().isoformat()}; no Lean needed to answer; this
folder is self-contained — zip it and send it as is).</p>
<div class="chips">
  <span><b>câu hỏi / queries</b> {len(queries)} ({open_q} OPEN)</span>
  <span class="pill st-BLOCKED">BLOCKED chunks: {len(blocked)}</span>
  <span><b>chunks in ledger</b> {len(recs)}</span>
</div>
{warn_html}
<div class="card question">
<h2>Cách trả lời / How to respond</h2>
<ol class="steps">
<li>Mở trang câu hỏi / open the query page (link in the table below).</li>
<li>Đọc “Câu hỏi dành cho tác giả” — mỗi trang có một câu hỏi duy nhất
    (một dòng sai trong bản in, hoặc một bước chứng minh không suy ra được).</li>
<li>Trang in có khung đỏ đánh dấu đúng vùng cần so — đó là căn cứ; công thức
    được dựng chữ bằng KaTeX (cần trình duyệt, không cần máy chủ).
    / Red boxes mark the exact printed region in question; formulas are
    typeset client-side.</li>
<li>Trả lời: gõ vào ô <i>Trả lời của tác giả</i> ở cuối trang rồi copy vào email,
    hoặc sửa tệp <code>reply-Q-NNN.md</code>.</li>
</ol>
</div>
<h2>Câu hỏi / Queries</h2>
<table>
<tr><th>ID</th><th>Title</th><th>Status</th><th>Chunk</th><th>PDF pages</th><th>Reply</th></tr>
{''.join(rows)}
</table>
<h2>Trạng thái từng bổ đề / Chunk status</h2>
<table>
<tr><th>Chunk</th><th>Status</th><th>Pages</th><th>Lean</th><th>Queries</th></tr>
{''.join(chunk_rows)}
</table>
<footer>
Sinh bởi / generated by <code>pipeline/05-feedback/render_report.py</code>;
nguồn sự thật / sources of truth: <code>pipeline/05-feedback/queries/</code> and
<code>pipeline/02-chunks/chunks/</code>. Do not edit generated files by hand.
</footer>"""

    title = "Báo cáo kiểm chứng / verification report"
    return ("<!doctype html>\n"
            f'<html lang="vi">\n<head>\n{head_assets(pack, title, False)}\n'
            f"</head>\n<body>\n{body}\n</body>\n</html>\n")


def build_reply(query: dict, rec: dict | None) -> str:
    lead = re.sub(r"[ \t]+\n", "\n", question_lead(query))
    return f"""# {query['id']} — trả lời của tác giả / author reply

- câu hỏi / question: {query['title']}
- chunk: {query['chunk'] or '?'}   PDF trang / pages: {page_list(rec)}
- trạng thái / status: {query['status']}

## Câu hỏi / Question

{lead}

## Trả lời / Answer

(your answer here — one sentence is enough when the correction is a sign, a
number, or a line reference)

## Đính chính bản in / Correction to the printed text (if any)

- trang / page:
- dòng / line:
- chữ đúng / correct text:

## Chữ ký / Signature

- họ tên / name:
- ngày / date:
"""


# --------------------------------------------------------------------------- #
# consistency checks, prune, verify
# --------------------------------------------------------------------------- #

def check(queries: list[dict], recs: dict[str, dict]) -> list[str]:
    warnings: list[str] = []
    query_ids = {q["id"] for q in queries}
    for q in queries:
        if q["chunk"] is None:
            warnings.append(f"{q['id']}: no chunk reference found")
        elif q["chunk"] not in recs:
            warnings.append(f"{q['id']}: references unknown chunk {q['chunk']}")
        for ref in IMAGE_REF_RE.findall(q["text"]):
            cand = ROOT / ref if ref.startswith("pipeline/") else HERE / ref
            if not cand.exists() and not (RENDER_DIR / Path(ref).name).exists():
                warnings.append(f"{q['id']}: image not found: {ref}")

    by_chunk: dict[str, list[str]] = {}
    for q in queries:
        if q["chunk"]:
            by_chunk.setdefault(q["chunk"], []).append(q["id"])
    for cid, rec in recs.items():
        if str(rec.get("status")) == "BLOCKED" and cid not in by_chunk:
            warnings.append(f"{cid}: BLOCKED but no author query references it")
        for qid in chunk_queries(rec):
            if qid not in query_ids:
                warnings.append(f"{cid}: mentions {qid}, but queries/{qid}-*.md is missing")
        for render in str(rec.get("renders", "")).split():
            if not (RENDER_DIR / render).exists():
                warnings.append(f"{cid}: render missing: {render}")
    return warnings


def prune(out_dir: Path) -> None:
    """Remove only what this script generated in *this* out dir (Gate 2:
    two report directories never share or inherit state)."""
    if not out_dir.exists():
        return
    entries = list(out_dir.iterdir())
    if not entries:
        return
    idx = out_dir / "index.html"
    if not (idx.exists() and MARKER
            in idx.read_text(encoding="utf-8", errors="replace")):
        print(f"error: {out_dir} exists but was not generated by {MARKER}; "
              f"refusing to delete it — use another --out", file=sys.stderr)
        raise SystemExit(2)
    for pattern in ("index.html", "Q-*.html", "reply-*.md", "*.zip"):
        for f in out_dir.glob(pattern):
            f.unlink()
    shutil.rmtree(out_dir / "assets", ignore_errors=True)


def _refs_in(text: str) -> list[str]:
    refs = list(re.findall(r"(?:src|href)=\"([^\"]+)\"", text))
    refs += [m[1] for m in re.findall(r"url\((['\"]?)([^)'\"]+)\1\)", text)]
    return refs


def verify(out_dir: Path, write_zip: bool) -> tuple[bool, str]:
    """Gate: zip the package, extract it elsewhere, and check that every
    reference resolves inside the extracted tree."""
    with tempfile.TemporaryDirectory() as tmp:
        tmp_path = Path(tmp)
        zpath = tmp_path / "report.zip"
        files = sorted(p for p in out_dir.rglob("*") if p.is_file())
        with zipfile.ZipFile(zpath, "w", zipfile.ZIP_DEFLATED) as zf:
            for f in files:
                zf.write(f, f.relative_to(out_dir).as_posix())
        if write_zip:
            ship = out_dir.parent / (out_dir.name + ".zip")
            shutil.copy2(zpath, ship)
        extract = tmp_path / "x"
        extract.mkdir()
        with zipfile.ZipFile(zpath) as zf:
            zf.extractall(extract)

        problems: list[str] = []
        refs = 0
        root = extract.resolve()
        for page in sorted(extract.rglob("*")):
            if not page.is_file():
                continue
            suffix = page.suffix.lower()
            if suffix in (".html", ".htm"):
                text = page.read_text(encoding="utf-8", errors="replace")
                targets = [(r, page) for r in _refs_in(text)]
            elif suffix == ".css":
                text = page.read_text(encoding="utf-8", errors="replace")
                targets = [(m[1], page) for m in re.findall(r"url\((['\"]?)([^)'\"]+)\1\)", text)]
            else:
                continue
            for ref, base in targets:
                if EXTERNAL_REF_RE.match(ref):
                    continue
                refs += 1
                clean = unquote(ref.split("#")[0].split("?")[0])
                if not clean:
                    continue
                target = (base.parent / clean).resolve()
                try:
                    target.relative_to(root)
                except ValueError:
                    problems.append(f"{page.relative_to(extract)}: {ref} escapes the package")
                    continue
                if not target.exists():
                    problems.append(f"{page.relative_to(extract)}: missing {ref}")
        # Structural gate: a packed stylesheet must keep every @font-face (each
        # with its url()) and the rule that binds KaTeX's families — otherwise
        # formulas silently fall back to system fonts and look wrong.
        for css in sorted(extract.rglob("*.css")):
            rel = css.relative_to(extract).as_posix()
            dst = css.read_text(encoding="utf-8", errors="replace")
            blocks = dst.count("@font-face")
            with_url = len(re.findall(r"@font-face\{[^}]*url\(", dst))
            if blocks and blocks != with_url:
                problems.append(f"{rel}: {blocks - with_url} @font-face block(s) "
                                f"lost their url() font")
            if rel.startswith("assets/"):
                src_path = PIPE / rel[len("assets/"):]
                if src_path.is_file():
                    src_text = src_path.read_text(encoding="utf-8", errors="replace")
                    if src_text.count("@font-face") != blocks:
                        problems.append(f"{rel}: @font-face count {blocks} != source "
                                        f"{src_text.count('@font-face')}")
                    if ".katex{" in src_text and ".katex{" not in dst:
                        problems.append(f"{rel}: lost the .katex rule (font binding)")
            else:
                problems.append(f"{rel}: stylesheet outside assets/")

        size_mb = zpath.stat().st_size / (1024 * 1024)
        msg = (f"verify: {len(files)} files, {refs} refs checked, "
               f"zip {size_mb:.1f} MB -> extracted clean"
               if not problems else
               "verify FAILED:\n  " + "\n  ".join(problems))
        return (not problems), msg


# --------------------------------------------------------------------------- #

def main() -> int:
    ap = argparse.ArgumentParser(description="author report for Lean findings")
    ap.add_argument("--out", default=str(DEFAULT_OUT), metavar="DIR",
                    help="output directory (default: %(default)s)")
    ap.add_argument("--quiet", action="store_true", help="only errors on stdout")
    ap.add_argument("--no-verify", action="store_true",
                    help="skip the zip/extract self-containment gate")
    ap.add_argument("--zip", action="store_true",
                    help="also write <out>.zip for shipping")
    args = ap.parse_args()

    query_files = sorted(p for p in QUERIES_DIR.glob("Q-*.md")
                         if "template" not in p.stem.lower())
    if not query_files:
        print(f"error: no queries in {QUERIES_DIR}", file=sys.stderr)
        return 1

    queries: list[dict] = []
    for path in query_files:
        try:
            queries.append(parse_query(path))
        except ValueError as exc:
            print(f"error: {exc}", file=sys.stderr)
            return 1

    recs: dict[str, dict] = {}
    for path in sorted(CHUNKS_DIR.glob("*.yml")):
        rec = parse_chunk(path)
        if rec.get("id"):
            recs[rec["id"]] = rec
    warnings = check(queries, recs)

    out_dir = Path(args.out)
    if not out_dir.is_absolute():
        out_dir = Path.cwd() / out_dir
    try:
        prune(out_dir)
        out_dir.mkdir(parents=True, exist_ok=True)
    except OSError as exc:
        print(f"error: cannot prepare {out_dir}: {exc}", file=sys.stderr)
        return 2

    pack = Pack(out_dir)
    try:
        # reply templates first: issue pages link to them
        for q in queries:
            rec = recs.get(q["chunk"] or "")
            (out_dir / f"reply-{q['id']}.md").write_text(
                build_reply(q, rec), encoding="utf-8", newline="\n")
        for q in queries:
            rec = recs.get(q["chunk"] or "")
            (out_dir / f"{q['id']}.html").write_text(
                build_issue_page(q, rec, pack), encoding="utf-8", newline="\n")
        (out_dir / "index.html").write_text(
            build_index(queries, recs, warnings, pack), encoding="utf-8", newline="\n")
        closure_added = pack.closure()
    except (OSError, FileNotFoundError) as exc:
        print(f"error: cannot build report: {exc}", file=sys.stderr)
        return 2

    ok, msg = True, "verify skipped (--no-verify)"
    if not args.no_verify:
        ok, msg = verify(out_dir, args.zip)
    if not args.quiet:
        print(f"report: {len(queries)} queries -> {out_dir / 'index.html'}")
        print(f"  packed {len(pack.map)} assets (+{closure_added} from linked pages), "
              f"{len(pack.html_queue)} linked pages")
        for q in queries:
            print(f"  {q['id']:<8} {q['status']:<9} chunk={q['chunk'] or '-':<12} "
                  f"{out_dir / (q['id'] + '.html')}")
        for d in pack.declined:
            print(f"  note: not packed (would drag the whole review surface): {d}")
        for w in warnings:
            print(f"  warning: {w}")
        print(f"  {msg}")
        if args.zip:
            print(f"  shipping archive: {out_dir.with_suffix('.zip')}")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
